include:
  - https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools/-/raw/main/gsi-port-ci.yml

variables:
  BUILD_DEVEL_FLASHABLE_FOCAL: "1"
  ADAPTATION_TOOLS_BRANCH: main
  ROOTFS_URL: "https://ci.ubports.com/job/ubuntu-touch-rootfs/job/main/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz"
  OTA_CHANNEL: "utnext/arm64/android9plus/daily"

devel-flashable:
  rules:
    - when: never

build:
  script:
    - apt update
    - >-
      apt install -y --no-install-recommends
      bc bison build-essential ca-certificates cpio curl
      fakeroot flex git kmod libelf-dev libssl-dev libtinfo5       lz4 python2 python3 sudo unzip wget
      xz-utils
    - ln -s python2 /usr/bin/python
    - git clone -b $ADAPTATION_TOOLS_BRANCH https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools.git build
    - ./build.sh
