include:
  - project: 'halium/halium-generic-adaptation-build-tools'
    ref: 'master'
    file: '/.gitlab-ci.yml'

variables:
  DEVICEINFO_NAME: "Xiaomi Pad 6"
  DEVICEINFO_CODENAME: "pipa"
  DEVICEINFO_MANUFACTURER: "Xiaomi"
  DEVICEINFO_ARCH: "aarch64"
  DEVICEINFO_HALIUM_VERSION: "13"
  DEVICEINFO_KERNEL_SOURCE: "https://github.com/aymanrgab/linux-android-xiaomi-pipa"
  DEVICEINFO_KERNEL_SOURCE_BRANCH: "main"
  DEVICEINFO_KERNEL_DEFCONFIG: "vendor/pipa_defconfig halium.config"
  DEVICEINFO_KERNEL_CLANG_COMPILE: "true"
  DEVICEINFO_KERNEL_IMAGE_NAME: "Image.gz-dtb"
  DEVICEINFO_BOOTIMG_HEADER_VERSION: "2"
  DEVICEINFO_BOOTIMG_PARTITION_SIZE: "100663296"
  DEVICEINFO_FLASH_PAGESIZE: "4096"
  DEVICEINFO_FLASH_OFFSET_BASE: "0x00000000"
  DEVICEINFO_FLASH_OFFSET_KERNEL: "0x00008000"
  DEVICEINFO_FLASH_OFFSET_RAMDISK: "0x01000000"
  DEVICEINFO_FLASH_OFFSET_SECOND: "0x00f00000"
  DEVICEINFO_FLASH_OFFSET_TAGS: "0x00000100"
  DEVICEINFO_FLASH_OFFSET_DTB: "0x01f00000"
  DEVICEINFO_KERNEL_CMDLINE: "rcupdate.rcu_expedited=1 rcu_nocbs=0-7 kpti=off cgroup_disable=pressure ramoops_memreserve=4M console=tty0"
  DEVICEINFO_USE_OVERLAYSTORE: "true"
  DEVICEINFO_SYSTEM_PARTITION_SIZE: "4096M"
  DEVICEINFO_HAS_RECOVERY_PARTITION: "true"
  DEVICEINFO_RECOVERY_PARTITION_SIZE: "100663296"
  DEVICEINFO_HAS_DTBO: "true"
  DEVICEINFO_ROOTFS_IMAGE_SECTOR_SIZE: "4096"
