[device]
# Give the Qualcomm cnss driver more time to initialize the firmware
wifi.scan-rand-mac-address=no

[connection]
# Increase the timeout limit for Wi-Fi association
wifi.auth-alg=open
ipv4.dhcp-timeout=60
