[hdr]
camera_id=-1
image=1

[zsl]
camera_id=-1
image=1

[edge-mode]
camera_id=-1
image=1
prop=edge-mode
on=high-quality
off=off

[noise-reduction]
camera_id=-1
image=1
prop=noise-reduction
on=high-quality
off=off
