# pipa cnss: one STA iface only; ignore driver extras.
[device]
wifi.p2p=false

[keyfile]
unmanaged-devices=interface-name:wlan1;interface-name:p2p0;interface-name:wifi-aware0;interface-name:p2p-dev-wlan0;interface-name:p2p-dev-wlp1s0;interface-name:p2p-dev-*

[device-wlan1]
match-device=interface-name:wlan1
managed=false

[device-p2p0]
match-device=interface-name:p2p0
managed=false

[device-wifi-aware0]
match-device=interface-name:wifi-aware0
managed=false

[device-p2p-dev]
match-device=interface-name:p2p-dev-*
managed=false
