# Device recovery config for Xiaomi Pad 6 (pipa)
DEVICE_NAME="Xiaomi Pad 6"
DEVICE_CODENAME="pipa"
DEVICE_MANUFACTURER="Xiaomi"
DEVICE_ARCH="aarch64"
DEVICE_AB="true"
DEVICE_HAS_DTBO="true"
DEVICE_BOOT_PARTITION_SIZE="100663296"
DEVICE_RECOVERY_PARTITION_SIZE="100663296"
