name: Build

on:
  push:
    branches: [ "main", "halium-13" ]
  pull_request:
    branches: [ "main", "halium-13" ]
  workflow_dispatch:

env:
  ADAPTATION_TOOLS_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            bc bison build-essential ca-certificates cpio curl \
            fakeroot flex git kmod libelf-dev libssl-dev libtinfo5 \
            lz4 python2 python3 sudo unzip wget xz-utils
          sudo ln -sf python2 /usr/bin/python
      - name: Clone build tools
        run: git clone -b $ADAPTATION_TOOLS_BRANCH https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools.git build
      - name: Run build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: out/

  flashable:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git img2simg jq sudo wget xz-utils
      - name: Clone build tools
        run: git clone -b $ADAPTATION_TOOLS_BRANCH https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools.git build
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out/
      - name: Prepare flashable
        run: |
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/fetch-and-prepare-latest-ota.sh "utnext/arm64/android9plus/daily" "$DEVICE" ota
          mkdir -p out_flashable
          ./build/system-image-from-ota.sh ota/ubuntu_command out_flashable
      - name: Upload flashable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flashable-output
          path: out_flashable/

  devel-flashable:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git img2simg jq sudo wget xz-utils zstd
      - name: Clone build tools
        run: git clone -b $ADAPTATION_TOOLS_BRANCH https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools.git build
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out/
      - name: Prepare devel flashable
        run: |
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/prepare-fake-ota.sh out/device_${DEVICE}.tar.xz ota
          mkdir -p out_devel
          ./build/system-image-from-ota.sh ota/ubuntu_command out_devel
          mv out_devel/rootfs.img out_devel/ubuntu.img
          zstd -15 -T0 out_devel/ubuntu.img
          rm -f out_devel/ubuntu.img
      - name: Upload devel flashable
        uses: actions/upload-artifact@v4
        with:
          name: devel-flashable-output
          path: out_devel/
